# Official docker compose image.
image:
  name: docker/compose:latest

services:
  - docker:dind

build:
  stage: build
  script:
    - screen -ls
    - docker-compose build --no-cache
    - screen -X -S sennai quit
    - screen -S sennai -dm docker-compose up 
